name: "OWASP ZAP DAST Full Scan"

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      actions: write

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Start the Node.js app in background
      - name: Start App in Background
        run: |
          nohup npm start &
          for i in {1..30}; do
            if curl -sSf http://localhost:3000 >/dev/null 2>&1; then
              echo "App is up"
              break
            fi
            echo "Waiting for app... ($i)"
            sleep 2
          done

      # 5️⃣ Run OWASP ZAP Full Scan
      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-a -m 5 -T 5'  # 5 min spider, 5 threads
          token: ${{ secrets.CUSTOME_GITHUB_PAT }}  # Use PAT with repo + workflow permissions

      # 6️⃣ Upload ZAP Reports as artifacts
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            report_html.html
            report_json.json
            report_xml.xml
