name: "DAST - OWASP ZAP"

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

env:
  NODE_VERSION: 18
  APP_PORT: 3000
  APP_START_CMD: "npm start"

jobs:
  dast:
    name: DAST Scan
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start your Node.js app in the background
      - name: Start App in Background
        run: |
          nohup ${{ env.APP_START_CMD }} &
          for i in {1..30}; do
            if curl -sSf http://localhost:${{ env.APP_PORT }}/ >/dev/null 2>&1; then
              echo "App is up"
              break
            fi
            echo "Waiting for app... ($i)"
            sleep 2
          done

      # Run OWASP ZAP Baseline Scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.8.0
        with:
          target: "http://localhost:${{ env.APP_PORT }}"
          fail_on_risk: "high"       # Fails job if high-risk issues found
          output_file: "zap_report.html"

      # Upload ZAP report as artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
