name: "DevSecOps: SAST + SCA + DAST"

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  security-events: write

env:
  NODE_VERSION: 18
  APP_PORT: 3000
  DEP_CHECK_VERSION: 12.1.0
  APP_START_CMD: "npm start"

jobs:
  # ----------------------------
  # SAST - CodeQL
  # ----------------------------
  sast:
    name: SAST - CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "sast"

  # ----------------------------
  # SCA - OWASP Dependency-Check
  # ----------------------------
  sca:
    name: SCA - Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Download Dependency-Check CLI
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v${{ env.DEP_CHECK_VERSION }}/dependency-check-${{ env.DEP_CHECK_VERSION }}-release.zip
          unzip dependency-check.zip

      - name: Run Dependency-Check
        run: |
          mkdir -p dependency-check-reports
          ./dependency-check/bin/dependency-check.sh \
            --project "$(basename $GITHUB_REPOSITORY)" \
            --scan ./ \
            --format ALL \
            --out ./dependency-check-reports \
            --failOnCVSS 7 || true

      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          path: dependency-check-reports
